# Generated by Django 5.2.7 on 2025-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_face_encoding_faceencoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceencoding',
            name='image',
        ),
    ]
