# Generated by Django 5.2.7 on 2025-12-09 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_faceencoding_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceencoding',
            options={},
        ),
        migrations.AddField(
            model_name='faceencoding',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceencoding',
            name='model_version',
            field=models.CharField(default='insightface_buffalo_l', max_length=50),
        ),
        migrations.AlterField(
            model_name='faceencoding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='faceencoding',
            name='encoding_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='faceencoding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='faceencoding',
            unique_together={('user', 'model_version')},
        ),
    ]
