# Generated by Django 5.2.7 on 2025-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_faceencoding_options_faceencoding_confidence_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='faceencoding',
            constraint=models.UniqueConstraint(fields=('user', 'model_version'), name='uniq_user_model_version'),
        ),
    ]
