# Generated by Django 5.2.7 on 2026-05-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_telegramprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='model_version',
            field=models.CharField(db_index=True, default='insightface_buffalo_l', max_length=50),
        ),
    ]
