# Generated by Django 5.2.7 on 2025-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camerascanresult',
            options={'ordering': ['ip'], 'verbose_name': 'Kamera skan natijasi', 'verbose_name_plural': 'Kamera skan natijalari'},
        ),
        migrations.AddField(
            model_name='camerascanresult',
            name='camera_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kamera turi'),
        ),
        migrations.AddField(
            model_name='camerascanresult',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kamera nomi'),
        ),
        migrations.AddField(
            model_name='camerascanresult',
            name='rtsp_url',
            field=models.URLField(blank=True, null=True, verbose_name='RTSP URL'),
        ),
        migrations.AlterField(
            model_name='camerascanresult',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP manzil'),
        ),
        migrations.AlterField(
            model_name='camerascanresult',
            name='port',
            field=models.IntegerField(verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='camerascanresult',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Skan vaqti'),
        ),
    ]
