# Generated by Django 5.2.7 on 2025-11-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_camerascanresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP manzil')),
                ('port', models.IntegerField(default=80, verbose_name='Port')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='Foydalanuvchi')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kamera nomi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kamera',
                'verbose_name_plural': 'Kameralar',
                'ordering': ['-is_active', 'ip'],
            },
        ),
        migrations.DeleteModel(
            name='CameraScanResult',
        ),
    ]
