# Generated by Django 5.2.7 on 2025-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_delete_camerascanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='enable_face_detection',
            field=models.BooleanField(default=False, verbose_name='Yuzni aniqlash yoqilsinmi?'),
        ),
    ]
