# Generated by GitHub Copilot on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_camera_enable_face_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(blank=True, null=True, verbose_name='RTSP URL'),
        ),
    ]
