# Generated by Django 5.2.7 on 2026-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_camera_enable_infraction_detection_infractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='infractionlog',
            name='offender_name',
            field=models.CharField(default='Shaxsi aniqlanmadi', max_length=100, verbose_name='Qoidabuzar shaxsi'),
        ),
        migrations.AddField(
            model_name='infractionlog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='infraction_videos/%Y/%m/%d/', verbose_name='Qisqa video'),
        ),
    ]
