# Generated by Django 5.2.7 on 2026-05-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_infractionlog_offender_name_infractionlog_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Auditoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh/Tavsif')),
                ('capacity', models.IntegerField(default=30, verbose_name="Sig'imi (talaba)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoriums', to='camera.camera', verbose_name='Kamera')),
            ],
            options={
                'verbose_name': 'Auditoriya',
                'verbose_name_plural': 'Auditoriyalar',
                'ordering': ['name'],
            },
        ),
    ]
