# Generated by Django 5.2.7 on 2026-05-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_auditorium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Fan nomi')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fan kodi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh/Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
    ]
