# Generated by Django 5.2.7 on 2026-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='degree_level',
            field=models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura'), ('doctoral', 'Doktorantura'), ('other', 'Boshqa')], default='bachelor', max_length=50, verbose_name="Ta'lim bosqichi"),
        ),
    ]
