# Generated by Django 5.2.7 on 2026-05-26 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_building_auditorium_building'),
        ('users', '0008_academicgroup_curriculum_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="O'qituvchi F.I.SH")),
                ('weekday', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni')),
                ('pair_number', models.IntegerField(choices=[(1, '1-para (08:30 - 09:50)'), (2, '2-para (10:00 - 11:20)'), (3, '3-para (11:30 - 12:50)'), (4, '4-para (13:30 - 14:50)'), (5, '5-para (15:00 - 16:20)'), (6, '6-para (16:30 - 17:50)')], verbose_name='Dars vaqti (Para)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.academicgroup', verbose_name='Akademik guruh')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='camera.auditorium', verbose_name='Auditoriya')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='camera.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['weekday', 'pair_number'],
                'unique_together': {('academic_group', 'weekday', 'pair_number')},
            },
        ),
    ]
