# Generated by Django 5.2.7 on 2026-05-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0012_lessonschedule'),
        ('users', '0008_academicgroup_curriculum_faculty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonschedule',
            options={'ordering': ['weekday', 'lesson_pair'], 'verbose_name': 'Dars jadvali', 'verbose_name_plural': 'Dars jadvallari'},
        ),
        migrations.CreateModel(
            name='LessonPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.IntegerField(choices=[(1, '1-smena'), (2, '2-smena'), (3, '3-smena')], default=1, verbose_name='Smena')),
                ('pair_number', models.IntegerField(verbose_name='Para raqami')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dars vaqti (Para)',
                'verbose_name_plural': 'Dars vaqtlari (Paralar)',
                'ordering': ['shift', 'pair_number'],
                'unique_together': {('shift', 'pair_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='lesson_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='camera.lessonpair', verbose_name='Dars vaqti (Para)'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('academic_group', 'weekday', 'lesson_pair')},
        ),
        migrations.RemoveField(
            model_name='lessonschedule',
            name='pair_number',
        ),
    ]
