# Generated by Django 5.2.7 on 2026-05-26 02:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0013_alter_lessonschedule_options_lessonpair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('summary_text', models.TextField(verbose_name='Dars xulosasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='camera.lessonschedule', verbose_name='Dars jadvali')),
            ],
            options={
                'verbose_name': 'Dars xulosasi',
                'verbose_name_plural': 'Dars xulosalari',
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
