# Generated by Django 5.2.7 on 2026-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_lessonsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infractionlog',
            name='infraction_type',
            field=models.CharField(choices=[('fight', 'Urush/Janjal'), ('smoking', 'Sigaret chekish'), ('sleeping', 'Darsda uxlash'), ('other', 'Boshqa huquqbuzarlik')], max_length=50, verbose_name='Huquqbuzarlik turi'),
        ),
    ]
