# Generated by Django 5.2.7 on 2026-05-28 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0015_alter_infractionlog_infraction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFaceCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Klaster nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_clusters', to=settings.AUTH_USER_MODEL, verbose_name="Bog'langan foydalanuvchi")),
            ],
            options={
                'verbose_name': "Noma'lum shaxs guruhi",
                'verbose_name_plural': "Noma'lum shaxslar guruhlari",
            },
        ),
        migrations.CreateModel(
            name='UnknownFaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unknown_faces/%Y/%m/%d/', verbose_name='Yuz surati')),
                ('encoding_data', models.JSONField(verbose_name="Vektor ma'lumotlari (embedding)")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aniqlangan vaqt')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_logs', to='camera.camera', verbose_name='Kamera')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces', to='camera.unknownfacecluster', verbose_name='Klaster')),
            ],
            options={
                'verbose_name': "Noma'lum yuz",
                'verbose_name_plural': "Noma'lum yuzlar",
                'ordering': ['-timestamp'],
            },
        ),
    ]
