# Generated by Django 5.2.7 on 2026-05-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0016_unknownfacecluster_unknownfacelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_entry_camera',
            field=models.BooleanField(default=False, verbose_name='Kirish kamerasimi?'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_exit_camera',
            field=models.BooleanField(default=False, verbose_name='Chiqish kamerasimi?'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_infraction_camera',
            field=models.BooleanField(default=False, verbose_name='Huquqbuzarlikni aniqlash kamerasimi?'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_lesson_camera',
            field=models.BooleanField(default=False, verbose_name='Dars jarayonini tahlil qilish kamerasimi?'),
        ),
    ]
