# Generated by Django 5.2.7 on 2026-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0017_camera_is_entry_camera_camera_is_exit_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsummary',
            name='diarized_transcript',
            field=models.JSONField(blank=True, default=list, verbose_name='Diarizatsiya qilingan matn'),
        ),
        migrations.AddField(
            model_name='lessonsummary',
            name='personal_life_distractions',
            field=models.IntegerField(default=0, verbose_name="Shaxsiy hayotga chalg'ishlar soni"),
        ),
        migrations.AddField(
            model_name='lessonsummary',
            name='professionalism_rating',
            field=models.CharField(default='Professional', max_length=100, verbose_name='Metodika professionalizmi'),
        ),
        migrations.AddField(
            model_name='lessonsummary',
            name='relevance_score',
            field=models.IntegerField(default=100, verbose_name='Mavzuga moslik foizi'),
        ),
    ]
