# Generated by Django 5.2.7 on 2026-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0018_lessonsummary_diarized_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='subjects/syllabuses/', verbose_name='Fan dasturi (Sillabus)'),
        ),
    ]
