# Generated by Django 5.2.7 on 2026-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0019_subject_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name="Dars o'tildi"),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', "Ma'ruza"), ('seminar', 'Seminar'), ('lab', 'Laboratoriya')], default='lecture', max_length=50, verbose_name='Dars turi'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dars mavzusi'),
        ),
    ]
