# Generated by Django 5.2.7 on 2026-07-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0020_lessonschedule_is_passed_lessonschedule_lesson_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('text', models.TextField(verbose_name='Transkript matni')),
                ('segment_index', models.IntegerField(default=0, verbose_name='Segment tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='camera.lessonschedule', verbose_name='Dars jadvali')),
            ],
            options={
                'verbose_name': 'Dars transkripti',
                'verbose_name_plural': 'Dars transkriptlari',
                'ordering': ['date', 'segment_index'],
            },
        ),
    ]
