# Generated by Django 5.2.7 on 2026-07-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0021_lessontranscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('planned_start', models.TimeField(blank=True, null=True, verbose_name='Rejalashtirilgan boshlanish')),
                ('planned_end', models.TimeField(blank=True, null=True, verbose_name='Rejalashtirilgan tugash')),
                ('teacher_started_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qituvchi darsni boshlagan vaqt")),
                ('teacher_ended_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qituvchi darsni tugatgan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='camera.lessonschedule', verbose_name='Dars jadvali')),
            ],
            options={
                'verbose_name': 'Dars sessiyasi',
                'verbose_name_plural': 'Dars sessiyalari',
                'ordering': ['-date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
