# Generated by Django 5.2.7 on 2026-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0022_add_lesson_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='analysis_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Tahlil natijalari'),
        ),
    ]
