# Generated by Codex on 2026-07-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camera', '0023_lesson_session_analysis_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Material nomi')),
                ('file', models.FileField(upload_to='lesson_materials/%Y/%m/%d/', verbose_name='Fayl')),
                ('material_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('presentation', 'Prezentatsiya'), ('document', 'Hujjat'), ('archive', 'Arxiv'), ('other', 'Boshqa')], default='other', max_length=30, verbose_name='Material turi')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Fayl hajmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='camera.lessonschedule', verbose_name='Dars jadvali')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_materials', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Dars materiali',
                'verbose_name_plural': 'Dars materiallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
