# Generated by Django 5.2.7 on 2026-08-18 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0024_lessonmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qurilma ID (Hikvision)')),
                ('channel_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kanal ID')),
                ('camera_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Kamera IP')),
                ('face_image', models.ImageField(upload_to='faces/%Y/%m/%d/', verbose_name='Yuz surati (Crop)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='faces_bg/%Y/%m/%d/', verbose_name='Umumiy kadr surati')),
                ('event_type', models.CharField(default='faceCapture', max_length=100, verbose_name='Voqea turi')),
                ('event_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voqea tavsifi')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Yuz ishonchliligi (Score)')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Taxminiy yosh')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Jinsi')),
                ('has_glasses', models.BooleanField(blank=True, null=True, verbose_name="Ko'zoynak")),
                ('has_mask', models.BooleanField(blank=True, null=True, verbose_name='Niqob')),
                ('face_rect', models.JSONField(blank=True, default=dict, verbose_name='Yuz koordinatalari')),
                ('similarity', models.FloatField(default=0.0, verbose_name='Moslik darajasi (Similarity)')),
                ('is_recognized', models.BooleanField(default=False, verbose_name='Shaxsi aniqlandimi?')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, verbose_name='Xom XML/JSON metadata')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tutilgan vaqt (Kameradan)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqt')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_logs', to='camera.camera', verbose_name='Kamera')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_logs', to=settings.AUTH_USER_MODEL, verbose_name='Tizim foydalanuvchisi')),
            ],
            options={
                'verbose_name': 'Yuz logi',
                'verbose_name_plural': 'Yuz loglari',
                'db_table': 'face_logs',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['-captured_at'], name='face_logs_capture_1325b1_idx'), models.Index(fields=['camera', '-captured_at'], name='face_logs_camera__2928b0_idx'), models.Index(fields=['matched_user', '-captured_at'], name='face_logs_matched_659e8c_idx')],
            },
        ),
    ]
