# Generated by Django 5.2.7 on 2026-08-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0025_facelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qurilma modeli'),
        ),
        migrations.AddField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC manzil'),
        ),
        migrations.AddField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seriya raqami'),
        ),
    ]
