# Generated by Django 5.2.7 on 2026-08-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0026_camera_device_model_camera_mac_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bino / Nazorat Punkti Nomi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif / Joylashuv')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqt')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_pairs', to='camera.building', verbose_name='Bino')),
                ('entry_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_pairs', to='camera.camera', verbose_name='Kirish kamerasi')),
                ('exit_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_pairs', to='camera.camera', verbose_name='Chiqish kamerasi')),
            ],
            options={
                'verbose_name': 'Kamera Juftligi (Nazorat Punkti)',
                'verbose_name_plural': 'Kamera Juftliklari (Nazorat Punktlari)',
                'ordering': ['name'],
            },
        ),
    ]
