# Generated by Django 5.2.7 on 2025-12-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0004_camera_enable_face_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rtmp_url', models.URLField(default='rtmp://a.rtmp.youtube.com/live2')),
                ('stream_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('failed', 'Failed')], default='stopped', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('ffmpeg_pid', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_streams', to='camera.camera')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='youtube.youtubeprofile')),
            ],
            options={
                'unique_together': {('camera', 'profile')},
            },
        ),
    ]
