# Generated by Django 5.2.7 on 2025-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
