# Generated by Django 5.2.7 on 2025-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtubeprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubestream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
