# Generated by Django 5.2.7 on 2025-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_youtubestream_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubestream',
            name='last_cmd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
