# Generated by Django 5.2.7 on 2025-10-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_status', models.CharField(choices=[('online', 'Online'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='online', help_text='Saytning hozirgi holati', max_length=20)),
                ('logo_dark', models.ImageField(blank=True, help_text='Saytning qora (dark) logosi', null=True, upload_to='site_logos/')),
                ('logo_light', models.ImageField(blank=True, help_text='Saytning oq (light) logosi', null=True, upload_to='site_logos/')),
                ('hemis_url', models.URLField(blank=True, help_text='HEMIS tizimining URL manzili', max_length=255)),
                ('hemis_api_token', models.CharField(blank=True, help_text='HEMIS API tokeni', max_length=255)),
                ('site_name', models.CharField(default='NamDPI', help_text='Sayt nomi', max_length=100)),
                ('contact_email', models.EmailField(blank=True, help_text='Asosiy kontakt email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Asosiy kontakt telefoni', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
