# Generated by Django 5.2.7 on 2025-11-17 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Sana')),
                ('first_seen', models.DateTimeField(blank=True, null=True, verbose_name='Birinchi marta ko‘rilgan')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Oxirgi marta ko‘rilgan')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('is_present', models.BooleanField(default=True, verbose_name='Hozirda mavjud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'indexes': [models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['user', 'date'], name='attendance__user_id_c01e0c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
