# Generated by Django 5.2.7 on 2025-11-17 11:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attendance_photos/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__date_61f2e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__user_id_c01e0c_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='first_seen',
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Binoda bo‘lgan vaqt (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='Hozirda binoda'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'is_present'], name='attendance__date_a84619_idx'),
        ),
        migrations.AddField(
            model_name='attendancephoto',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='attendance.attendance'),
        ),
    ]
