# Generated by Django 5.2.7 on 2025-11-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancephoto_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_emotion', models.CharField(blank=True, help_text='Masalan: happy, sad, angry, neutral, surprised...', max_length=50, null=True)),
                ('stress_level', models.FloatField(default=0, help_text='0.0 - 1.0 oralig‘ida stress darajasi')),
                ('energy_level', models.FloatField(default=0, help_text='0.0 - 1.0 oralig‘ida energiya darajasi')),
                ('mood_score', models.IntegerField(default=50, help_text='0 - 100 oralig‘ida psixologik holat')),
                ('summary_text', models.TextField(blank=True, help_text='AI tomonidan yaratilgan psixologik tavsif', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychology', to='attendance.attendance')),
            ],
            options={
                'verbose_name': 'Psixologik Portret',
                'verbose_name_plural': 'Psixologik Portretlar',
            },
        ),
    ]
