# Generated by Django 5.2.7 on 2025-12-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_psychologicalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='face_processing_device',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', help_text='Face encoding va face recognition qaysi qurilmada ishlasin', max_length=10),
        ),
    ]
