# Generated by Django 5.2.7 on 2025-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_sitesettings_face_processing_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt sozlamalari', 'verbose_name_plural': 'Sayt sozlamalari'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_dark',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_light',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_large',
            field=models.ImageField(blank=True, help_text='Saytning asosiy logosi (katta o‘lcham, masalan: header uchun)', null=True, upload_to='site_logos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_small',
            field=models.ImageField(blank=True, help_text='Saytning kichik logosi (masalan: navbar, favicon yonida)', null=True, upload_to='site_logos/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Kontakt email', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Kontakt telefon', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='face_processing_device',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', help_text='Face recognition qaysi qurilmada ishlasin', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hemis_api_token',
            field=models.CharField(blank=True, help_text='HEMIS API token', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hemis_url',
            field=models.URLField(blank=True, help_text='HEMIS API URL', max_length=255),
        ),
    ]
