# Generated by Django 5.2.7 on 2025-12-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalprofile',
            name='arousal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='emotion_probs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='face_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='negative_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='neutral_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='photo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='positive_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='stability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='psychologicalprofile',
            name='valence',
            field=models.FloatField(default=0.0),
        ),
    ]
