# Generated by Django 5.2.7 on 2025-12-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_psychologicalprofile_arousal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_auto_face_encoding',
            field=models.BooleanField(default=False, help_text='Agar yoqilgan bo‘lsa, foydalanuvchi rasm yuklaganda avtomatik face encoding yaratiladi'),
        ),
    ]
