# Generated by Django 5.2.7 on 2025-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_sitesettings_enable_auto_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bot_token',
            field=models.CharField(blank=True, default='', help_text='Bot token (masalan: Telegram bot token)', max_length=255),
        ),
    ]
