# Generated by Django 5.2.7 on 2026-05-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendance_entry_camera_attendance_exit_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanuvchi ismi')),
                ('position', models.CharField(max_length=255, verbose_name="Lavozimi/Bo'limi")),
                ('feedback_type', models.CharField(choices=[('taklif', 'Taklif'), ('xato', 'Xato topdim'), ('rahmat', 'Rahmat aytmoqchiman')], default='taklif', max_length=20, verbose_name='Fikr turi')),
                ('rating', models.IntegerField(default=5, verbose_name='Baholash (1-5)')),
                ('message', models.TextField(verbose_name='Fikr/Taklif matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Fikr-taklif / Xabar',
                'verbose_name_plural': 'Fikr-takliflar / Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
