# Generated by Django 5.2.7 on 2026-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='detection_count',
            field=models.IntegerField(default=1, verbose_name='Tanishlar soni'),
        ),
    ]
