# Generated by Django 5.2.7 on 2026-08-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_detection_count'),
        ('camera', '0026_camera_device_model_camera_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_seen_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_attendances', to='camera.camera', verbose_name="Oxirgi ko'rilgan kamera"),
        ),
    ]
